// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateEnvironmentData, CreateEnvironmentErrors, CreateEnvironmentResponses, ListEnvironmentsData, ListEnvironmentsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Environment {
    /**
     * Read Environments
     */
    public static listEnvironments<ThrowOnError extends boolean = false>(options?: Options<ListEnvironmentsData, ThrowOnError>) {
        return (options?.client ?? client).get<ListEnvironmentsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/environment',
            ...options
        });
    }
    
    /**
     * Create Environment
     */
    public static createEnvironment<ThrowOnError extends boolean = false>(options: Options<CreateEnvironmentData, ThrowOnError>) {
        return (options.client ?? client).post<CreateEnvironmentResponses, CreateEnvironmentErrors, ThrowOnError>({
            responseType: 'json',
            url: '/environment',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
