// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateEnvironmentData, CreateEnvironmentErrors, CreateEnvironmentHistoryData, CreateEnvironmentHistoryErrors, CreateEnvironmentHistoryResponses, CreateEnvironmentProfileData, CreateEnvironmentProfileErrors, CreateEnvironmentProfileResponses, CreateEnvironmentResponses, CreatePlantData, CreatePlantErrors, CreatePlantResponses, GetEnvironmentData, GetEnvironmentErrors, GetEnvironmentProfileData, GetEnvironmentProfileErrors, GetEnvironmentProfileResponses, GetEnvironmentResponses, GetLatestEnvironmentHistoryData, GetLatestEnvironmentHistoryErrors, GetLatestEnvironmentHistoryResponses, ListEnvironmentProfilesData, ListEnvironmentProfilesResponses, ListEnvironmentsData, ListEnvironmentsResponses, ListPlantsData, ListPlantsResponses, UpdateEnvironmentData, UpdateEnvironmentErrors, UpdateEnvironmentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Environment {
    /**
     * Get Environments
     */
    public static listEnvironments<ThrowOnError extends boolean = false>(options?: Options<ListEnvironmentsData, ThrowOnError>) {
        return (options?.client ?? client).get<ListEnvironmentsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/environment',
            ...options
        });
    }
    
    /**
     * Post Environment
     */
    public static createEnvironment<ThrowOnError extends boolean = false>(options: Options<CreateEnvironmentData, ThrowOnError>) {
        return (options.client ?? client).post<CreateEnvironmentResponses, CreateEnvironmentErrors, ThrowOnError>({
            responseType: 'json',
            url: '/environment',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Environment
     */
    public static getEnvironment<ThrowOnError extends boolean = false>(options: Options<GetEnvironmentData, ThrowOnError>) {
        return (options.client ?? client).get<GetEnvironmentResponses, GetEnvironmentErrors, ThrowOnError>({
            responseType: 'json',
            url: '/environment/{id}',
            ...options
        });
    }
    
    /**
     * Patch Environment
     */
    public static updateEnvironment<ThrowOnError extends boolean = false>(options: Options<UpdateEnvironmentData, ThrowOnError>) {
        return (options.client ?? client).patch<UpdateEnvironmentResponses, UpdateEnvironmentErrors, ThrowOnError>({
            responseType: 'json',
            url: '/environment/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class EnvironmentHistory {
    /**
     * Get Latest Environment History
     */
    public static getLatestEnvironmentHistory<ThrowOnError extends boolean = false>(options: Options<GetLatestEnvironmentHistoryData, ThrowOnError>) {
        return (options.client ?? client).get<GetLatestEnvironmentHistoryResponses, GetLatestEnvironmentHistoryErrors, ThrowOnError>({
            responseType: 'json',
            url: '/environment-history/latest/{environmentId}',
            ...options
        });
    }
    
    /**
     * Post Environment History
     */
    public static createEnvironmentHistory<ThrowOnError extends boolean = false>(options: Options<CreateEnvironmentHistoryData, ThrowOnError>) {
        return (options.client ?? client).post<CreateEnvironmentHistoryResponses, CreateEnvironmentHistoryErrors, ThrowOnError>({
            responseType: 'json',
            url: '/environment-history',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class EnvironmentProfile {
    /**
     * Get Environment Profiles
     */
    public static listEnvironmentProfiles<ThrowOnError extends boolean = false>(options?: Options<ListEnvironmentProfilesData, ThrowOnError>) {
        return (options?.client ?? client).get<ListEnvironmentProfilesResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/environment-profile',
            ...options
        });
    }
    
    /**
     * Post Environment Profile
     */
    public static createEnvironmentProfile<ThrowOnError extends boolean = false>(options: Options<CreateEnvironmentProfileData, ThrowOnError>) {
        return (options.client ?? client).post<CreateEnvironmentProfileResponses, CreateEnvironmentProfileErrors, ThrowOnError>({
            responseType: 'json',
            url: '/environment-profile',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Environment Profile
     */
    public static getEnvironmentProfile<ThrowOnError extends boolean = false>(options: Options<GetEnvironmentProfileData, ThrowOnError>) {
        return (options.client ?? client).get<GetEnvironmentProfileResponses, GetEnvironmentProfileErrors, ThrowOnError>({
            responseType: 'json',
            url: '/environment-profile/{id}',
            ...options
        });
    }
}

export class Plant {
    /**
     * Read Plants
     */
    public static listPlants<ThrowOnError extends boolean = false>(options?: Options<ListPlantsData, ThrowOnError>) {
        return (options?.client ?? client).get<ListPlantsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/plant',
            ...options
        });
    }
    
    /**
     * Create Plant
     */
    public static createPlant<ThrowOnError extends boolean = false>(options: Options<CreatePlantData, ThrowOnError>) {
        return (options.client ?? client).post<CreatePlantResponses, CreatePlantErrors, ThrowOnError>({
            responseType: 'json',
            url: '/plant',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
