// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * Environment
 *
 * Represents the Environment that Plants grow in. This could be a room in a building or a tent.
 */
export type Environment = {
    /**
     * Created At
     */
    created_at?: number;
    /**
     * Updated At
     */
    updated_at?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Can Id
     */
    can_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Plant
 *
 * A Plant node that monitors a single real world plant.
 */
export type Plant = {
    /**
     * Created At
     */
    created_at?: number;
    /**
     * Updated At
     */
    updated_at?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Species
     */
    species: string;
    /**
     * Name
     */
    name: string;
    /**
     * Can Id
     */
    can_id: string;
    /**
     * Environment Id
     */
    environment_id?: number | null;
    /**
     * Auto Watering
     */
    auto_watering: boolean;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListEnvironmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/environment';
};

export type ListEnvironmentsResponses = {
    /**
     * Response Listenvironments
     *
     * Successful Response
     */
    200: Array<Environment>;
};

export type ListEnvironmentsResponse = ListEnvironmentsResponses[keyof ListEnvironmentsResponses];

export type CreateEnvironmentData = {
    body: Environment;
    path?: never;
    query?: never;
    url: '/environment';
};

export type CreateEnvironmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEnvironmentError = CreateEnvironmentErrors[keyof CreateEnvironmentErrors];

export type CreateEnvironmentResponses = {
    /**
     * Successful Response
     */
    200: Environment;
};

export type CreateEnvironmentResponse = CreateEnvironmentResponses[keyof CreateEnvironmentResponses];

export type ListPlantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plant';
};

export type ListPlantsResponses = {
    /**
     * Response Listplants
     *
     * Successful Response
     */
    200: Array<Plant>;
};

export type ListPlantsResponse = ListPlantsResponses[keyof ListPlantsResponses];

export type CreatePlantData = {
    body: Plant;
    path?: never;
    query?: never;
    url: '/plant';
};

export type CreatePlantErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePlantError = CreatePlantErrors[keyof CreatePlantErrors];

export type CreatePlantResponses = {
    /**
     * Successful Response
     */
    200: Plant;
};

export type CreatePlantResponse = CreatePlantResponses[keyof CreatePlantResponses];
