// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * EnvironmentCreate
 *
 * Schema for POST requests
 */
export type EnvironmentCreate = {
    /**
     * Can Id
     */
    can_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Descr
     */
    descr?: string;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * EnvironmentHistoryCreate
 *
 * Schema for POST requests
 */
export type EnvironmentHistoryCreate = {
    /**
     * Environment Id
     */
    environment_id: number | null;
    /**
     * Environment Profile Id
     */
    environment_profile_id: number | null;
    /**
     * Light Status
     */
    light_status: boolean | null;
    /**
     * Heat Status
     */
    heat_status: boolean | null;
    /**
     * Temperature
     */
    temperature: number | null;
    /**
     * Humidity
     */
    humidity: number | null;
    /**
     * Gas
     */
    gas: number | null;
};

/**
 * EnvironmentHistoryPublic
 *
 * Schema for GET response
 */
export type EnvironmentHistoryPublic = {
    /**
     * Id
     */
    id: number | null;
    /**
     * Environment Id
     */
    environment_id: number | null;
    /**
     * Environment Profile Id
     */
    environment_profile_id: number | null;
    /**
     * Light Status
     */
    light_status: boolean | null;
    /**
     * Heat Status
     */
    heat_status: boolean | null;
    /**
     * Temperature
     */
    temperature: number | null;
    /**
     * Humidity
     */
    humidity: number | null;
    /**
     * Gas
     */
    gas: number | null;
    /**
     * Datetime
     */
    datetime: number;
};

/**
 * EnvironmentPatch
 *
 * Schema for PATCH requests
 */
export type EnvironmentPatch = {
    /**
     * Can Id
     */
    can_id?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Descr
     */
    descr?: string;
    /**
     * Environment Profile Id
     */
    environment_profile_id: number | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * EnvironmentProfileCreate
 *
 * Schema for POST requests
 */
export type EnvironmentProfileCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Descr
     */
    descr?: string;
};

/**
 * EnvironmentProfilePublic
 *
 * Schema for GET response
 */
export type EnvironmentProfilePublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Name
     */
    name: string;
    /**
     * Descr
     */
    descr?: string | null;
};

/**
 * EnvironmentPublic
 *
 * Schema for GET response
 */
export type EnvironmentPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Can Id
     */
    can_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Descr
     */
    descr?: string | null;
    /**
     * Environment Profile Id
     */
    environment_profile_id: number | null;
    /**
     * Sort Order
     */
    sort_order: number;
};

/**
 * EnvironmentTargetCreate
 *
 * Schema for POST requests
 */
export type EnvironmentTargetCreate = {
    /**
     * Environment Profile Id
     */
    environment_profile_id: number;
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Light Status
     */
    light_status: boolean;
    /**
     * Target Temperature
     */
    target_temperature: number;
    /**
     * Target Humidity
     */
    target_humidity: number;
};

/**
 * EnvironmentTargetPublic
 *
 * Schema for GET response
 */
export type EnvironmentTargetPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Environment Profile Id
     */
    environment_profile_id: number;
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Light Status
     */
    light_status: boolean;
    /**
     * Target Temperature
     */
    target_temperature: number;
    /**
     * Target Humidity
     */
    target_humidity: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PlantCreate
 *
 * Schema for POST requests
 */
export type PlantCreate = {
    /**
     * Species
     */
    species: string;
    /**
     * Name
     */
    name: string;
    /**
     * Can Id
     */
    can_id: string;
    /**
     * Environment Id
     */
    environment_id: number;
    /**
     * Auto Watering
     */
    auto_watering: boolean;
    /**
     * Sort Order
     */
    sort_order: number;
};

/**
 * PlantPublic
 *
 * Schema for GET response
 */
export type PlantPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Species
     */
    species: string;
    /**
     * Name
     */
    name: string;
    /**
     * Can Id
     */
    can_id: string;
    /**
     * Environment Id
     */
    environment_id: number;
    /**
     * Auto Watering
     */
    auto_watering: boolean;
    /**
     * Sort Order
     */
    sort_order: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListEnvironmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/environment';
};

export type ListEnvironmentsResponses = {
    /**
     * Response Listenvironments
     *
     * Successful Response
     */
    200: Array<EnvironmentPublic>;
};

export type ListEnvironmentsResponse = ListEnvironmentsResponses[keyof ListEnvironmentsResponses];

export type CreateEnvironmentData = {
    body: EnvironmentCreate;
    path?: never;
    query?: never;
    url: '/environment';
};

export type CreateEnvironmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEnvironmentError = CreateEnvironmentErrors[keyof CreateEnvironmentErrors];

export type CreateEnvironmentResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentPublic;
};

export type CreateEnvironmentResponse = CreateEnvironmentResponses[keyof CreateEnvironmentResponses];

export type GetEnvironmentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: {
        /**
         * Include Inactive
         */
        include_inactive?: boolean;
    };
    url: '/environment/{id}';
};

export type GetEnvironmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEnvironmentError = GetEnvironmentErrors[keyof GetEnvironmentErrors];

export type GetEnvironmentResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentPublic;
};

export type GetEnvironmentResponse = GetEnvironmentResponses[keyof GetEnvironmentResponses];

export type UpdateEnvironmentData = {
    body: EnvironmentPatch;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/environment/{id}';
};

export type UpdateEnvironmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEnvironmentError = UpdateEnvironmentErrors[keyof UpdateEnvironmentErrors];

export type UpdateEnvironmentResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentPublic;
};

export type UpdateEnvironmentResponse = UpdateEnvironmentResponses[keyof UpdateEnvironmentResponses];

export type GetLatestEnvironmentHistoryData = {
    body?: never;
    path: {
        /**
         * Environmentid
         */
        environmentId: number;
    };
    query?: never;
    url: '/environment-history/latest/{environmentId}';
};

export type GetLatestEnvironmentHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLatestEnvironmentHistoryError = GetLatestEnvironmentHistoryErrors[keyof GetLatestEnvironmentHistoryErrors];

export type GetLatestEnvironmentHistoryResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentHistoryPublic;
};

export type GetLatestEnvironmentHistoryResponse = GetLatestEnvironmentHistoryResponses[keyof GetLatestEnvironmentHistoryResponses];

export type CreateEnvironmentHistoryData = {
    body: EnvironmentHistoryCreate;
    path?: never;
    query?: never;
    url: '/environment-history';
};

export type CreateEnvironmentHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEnvironmentHistoryError = CreateEnvironmentHistoryErrors[keyof CreateEnvironmentHistoryErrors];

export type CreateEnvironmentHistoryResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentHistoryPublic;
};

export type CreateEnvironmentHistoryResponse = CreateEnvironmentHistoryResponses[keyof CreateEnvironmentHistoryResponses];

export type ListEnvironmentProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/environment-profile';
};

export type ListEnvironmentProfilesResponses = {
    /**
     * Response Listenvironmentprofiles
     *
     * Successful Response
     */
    200: Array<EnvironmentProfilePublic>;
};

export type ListEnvironmentProfilesResponse = ListEnvironmentProfilesResponses[keyof ListEnvironmentProfilesResponses];

export type CreateEnvironmentProfileData = {
    body: EnvironmentProfileCreate;
    path?: never;
    query?: never;
    url: '/environment-profile';
};

export type CreateEnvironmentProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEnvironmentProfileError = CreateEnvironmentProfileErrors[keyof CreateEnvironmentProfileErrors];

export type CreateEnvironmentProfileResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentProfilePublic;
};

export type CreateEnvironmentProfileResponse = CreateEnvironmentProfileResponses[keyof CreateEnvironmentProfileResponses];

export type GetEnvironmentProfileData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: {
        /**
         * Include Inactive
         */
        include_inactive?: boolean;
    };
    url: '/environment-profile/{id}';
};

export type GetEnvironmentProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEnvironmentProfileError = GetEnvironmentProfileErrors[keyof GetEnvironmentProfileErrors];

export type GetEnvironmentProfileResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentProfilePublic;
};

export type GetEnvironmentProfileResponse = GetEnvironmentProfileResponses[keyof GetEnvironmentProfileResponses];

export type GetEnvironmentTargetsForProfileData = {
    body?: never;
    path: {
        /**
         * Environmentprofileid
         */
        environmentProfileId: number;
    };
    query?: never;
    url: '/environment-target/{environmentProfileId}';
};

export type GetEnvironmentTargetsForProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEnvironmentTargetsForProfileError = GetEnvironmentTargetsForProfileErrors[keyof GetEnvironmentTargetsForProfileErrors];

export type GetEnvironmentTargetsForProfileResponses = {
    /**
     * Response Getenvironmenttargetsforprofile
     *
     * Successful Response
     */
    200: Array<EnvironmentTargetPublic>;
};

export type GetEnvironmentTargetsForProfileResponse = GetEnvironmentTargetsForProfileResponses[keyof GetEnvironmentTargetsForProfileResponses];

export type CreateEnvironmentTargetData = {
    body: EnvironmentTargetCreate;
    path?: never;
    query?: never;
    url: '/environment-target';
};

export type CreateEnvironmentTargetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEnvironmentTargetError = CreateEnvironmentTargetErrors[keyof CreateEnvironmentTargetErrors];

export type CreateEnvironmentTargetResponses = {
    /**
     * Successful Response
     */
    200: EnvironmentTargetPublic;
};

export type CreateEnvironmentTargetResponse = CreateEnvironmentTargetResponses[keyof CreateEnvironmentTargetResponses];

export type ListPlantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plant';
};

export type ListPlantsResponses = {
    /**
     * Response Listplants
     *
     * Successful Response
     */
    200: Array<PlantPublic>;
};

export type ListPlantsResponse = ListPlantsResponses[keyof ListPlantsResponses];

export type CreatePlantData = {
    body: PlantCreate;
    path?: never;
    query?: never;
    url: '/plant';
};

export type CreatePlantErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePlantError = CreatePlantErrors[keyof CreatePlantErrors];

export type CreatePlantResponses = {
    /**
     * Successful Response
     */
    200: PlantPublic;
};

export type CreatePlantResponse = CreatePlantResponses[keyof CreatePlantResponses];

export type GetLiveEnvironmentHistoryLiveEnvironmentHistoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/live/environment-history';
};

export type GetLiveEnvironmentHistoryLiveEnvironmentHistoryGetResponses = {
    /**
     * Response Get Live Environment History Live Environment History Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetLiveEnvironmentHistoryLiveEnvironmentHistoryGetResponse = GetLiveEnvironmentHistoryLiveEnvironmentHistoryGetResponses[keyof GetLiveEnvironmentHistoryLiveEnvironmentHistoryGetResponses];

export type CreateLiveEnvironmentHistoryData = {
    body: EnvironmentHistoryCreate;
    path?: never;
    query?: never;
    url: '/live/environment-history';
};

export type CreateLiveEnvironmentHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLiveEnvironmentHistoryError = CreateLiveEnvironmentHistoryErrors[keyof CreateLiveEnvironmentHistoryErrors];

export type CreateLiveEnvironmentHistoryResponses = {
    /**
     * Response Createliveenvironmenthistory
     *
     * Successful Response
     */
    200: number;
};

export type CreateLiveEnvironmentHistoryResponse = CreateLiveEnvironmentHistoryResponses[keyof CreateLiveEnvironmentHistoryResponses];

export type GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetData = {
    body?: never;
    path: {
        /**
         * Environmentid
         */
        environmentId: number;
    };
    query?: never;
    url: '/live/environment-history/{environmentId}';
};

export type GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetError = GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetErrors[keyof GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetErrors];

export type GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetResponses = {
    /**
     * Response Get Live Environment History By Group Live Environment History  Environmentid  Get
     *
     * Successful Response
     */
    200: Array<EnvironmentHistoryPublic>;
};

export type GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetResponse = GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetResponses[keyof GetLiveEnvironmentHistoryByGroupLiveEnvironmentHistoryEnvironmentIdGetResponses];
