// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Environment
 *
 * Represents the Environment that Plants grow in. This could be a room in a building or a tent.
 */
export type Environment = {
    /**
     * Created At
     */
    created_at?: number;
    /**
     * Updated At
     */
    updated_at?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Can Id
     */
    can_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * EnvironmentProfile
 *
 * Represents a grouping of EnvironmentTarget settings.
 *
 * Examples:
 * - "Seedling": Lights are on continuously.
 * - "Growth Stage": Lights are on 18h per day.
 */
export type EnvironmentProfile = {
    /**
     * Created At
     */
    created_at?: number;
    /**
     * Updated At
     */
    updated_at?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Descr
     */
    descr: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Plant
 *
 * A Plant node that monitors a single real world plant.
 */
export type Plant = {
    /**
     * Created At
     */
    created_at?: number;
    /**
     * Updated At
     */
    updated_at?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Species
     */
    species: string;
    /**
     * Name
     */
    name: string;
    /**
     * Can Id
     */
    can_id: string;
    /**
     * Environment Id
     */
    environment_id?: number | null;
    /**
     * Auto Watering
     */
    auto_watering: boolean;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadEnvironmentsEnvironmentGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/environment';
};

export type ReadEnvironmentsEnvironmentGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateEnvironmentEnvironmentPostData = {
    body: Environment;
    path?: never;
    query?: never;
    url: '/environment';
};

export type CreateEnvironmentEnvironmentPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEnvironmentEnvironmentPostError = CreateEnvironmentEnvironmentPostErrors[keyof CreateEnvironmentEnvironmentPostErrors];

export type CreateEnvironmentEnvironmentPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadEnvironmentProfilesEnvironmentProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/environment/profile';
};

export type ReadEnvironmentProfilesEnvironmentProfileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateEnvironmentProfileEnvironmentProfilePostData = {
    body: EnvironmentProfile;
    path?: never;
    query?: never;
    url: '/environment/profile';
};

export type CreateEnvironmentProfileEnvironmentProfilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEnvironmentProfileEnvironmentProfilePostError = CreateEnvironmentProfileEnvironmentProfilePostErrors[keyof CreateEnvironmentProfileEnvironmentProfilePostErrors];

export type CreateEnvironmentProfileEnvironmentProfilePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadPlantsPlantGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plant';
};

export type ReadPlantsPlantGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreatePlantPlantPostData = {
    body: Plant;
    path?: never;
    query?: never;
    url: '/plant';
};

export type CreatePlantPlantPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePlantPlantPostError = CreatePlantPlantPostErrors[keyof CreatePlantPlantPostErrors];

export type CreatePlantPlantPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
